// Research paper draft: LEO mega-constellation Kessler risk simulation
const fs = require("fs");
const {
  Document, Packer, Paragraph, TextRun, ImageRun, HeadingLevel,
  AlignmentType, Table, TableRow, TableCell, WidthType, BorderStyle,
  ShadingType, Math: DMath, MathRun, MathFraction, MathSubScript,
  MathSuperScript,
} = require("docx");

const FONT = "Times New Roman";
const r = (t, o = {}) => new TextRun({ text: t, font: FONT, size: 22, ...o });
const p = (children, o = {}) =>
  new Paragraph({
    children: Array.isArray(children) ? children : [r(children)],
    alignment: AlignmentType.JUSTIFIED,
    spacing: { after: 160, line: 276 },
    ...o,
  });
const h1 = (t) =>
  new Paragraph({ heading: HeadingLevel.HEADING_1, spacing: { before: 320, after: 160 },
    children: [new TextRun({ text: t, font: FONT, size: 28, bold: true, color: "1a1a2e" })] });
const h2 = (t) =>
  new Paragraph({ heading: HeadingLevel.HEADING_2, spacing: { before: 240, after: 120 },
    children: [new TextRun({ text: t, font: FONT, size: 24, bold: true, color: "1a1a2e" })] });
const eq = (runs) =>
  new Paragraph({ alignment: AlignmentType.CENTER, spacing: { before: 120, after: 160 },
    children: runs });
const it = (t) => r(t, { italics: true });
const sub = (t) => r(t, { subScript: true, italics: true });
const sup = (t) => r(t, { superScript: true });
// inline math run fragments (Word superscript/subscript formatting)
const mN090 = () => [it("N"), r("0.90", { superScript: true, italics: true })];
const mClosure = () => [it("R"), sub("0"), r(" = "), it("aN"),
  r("0.90", { superScript: true, italics: true }), r("/(1 − "), it("N"),
  r("/"), it("N"), r("*", { superScript: true }), r(")")];
const eqnum = (n) => new TextRun({ text: "      (" + n + ")", font: FONT, size: 22 });

const caption = (t) =>
  new Paragraph({ alignment: AlignmentType.CENTER, spacing: { after: 240 },
    children: [new TextRun({ text: t, font: FONT, size: 20, italics: true, color: "444444" })] });
const img = (path, w, hgt) =>
  new Paragraph({ alignment: AlignmentType.CENTER, spacing: { before: 160, after: 60 },
    children: [new ImageRun({ type: "png", data: fs.readFileSync(path),
      transformation: { width: w, height: hgt } })] });

// ---------- tables ----------
// ---------- pseudocode block ----------
const codeLine = (t, indent = 0) =>
  new Paragraph({
    spacing: { after: 20, line: 240 },
    children: [new TextRun({ text: " ".repeat(indent * 3) + t,
      font: "Consolas", size: 17 })],
  });
const algoBlock = (lines) =>
  new Table({
    columnWidths: [9360], width: { size: 9360, type: WidthType.DXA },
    rows: [new TableRow({ children: [new TableCell({
      width: { size: 9360, type: WidthType.DXA },
      borders: { top: { style: BorderStyle.SINGLE, size: 6, color: "444444" },
                 bottom: { style: BorderStyle.SINGLE, size: 6, color: "444444" },
                 left: { style: BorderStyle.SINGLE, size: 2, color: "cccccc" },
                 right: { style: BorderStyle.SINGLE, size: 2, color: "cccccc" } },
      shading: { type: ShadingType.CLEAR, fill: "f5f6f8" },
      margins: { top: 120, bottom: 120, left: 160, right: 160 },
      children: lines.map(([t, i]) => codeLine(t, i)),
    })] })],
  });

const algo1 = algoBlock([
  ["Algorithm 1 — one Monte Carlo history (time step Δt = 5 d)", 0],
  ["input:  N satellites; parameters of Table 2; RNG seed", 0],
  ["initialize Walker shell (planes, in-plane phasing, staggered ages)", 0],
  ["for each time step t = 0 ... 100 yr:", 0],
  ["-- 1. propagate all objects (vectorized over the population) --", 1],
  ["Ω ← Ω + (dΩ/dt)|J2 · Δt ;  u ← u + n·Δt", 2],
  ["a ← a + (da/dt)|drag · (1 + 20% noise) · Δt ;  damp e", 2],
  ["-- 2. operational control loop (active satellites only) --", 1],
  ["if a < a_nom − 500 m:  re-boost to a_nom + 500 m ; record ΔV", 2],
  ["if age > 7 yr:  deorbit (prob. PMD) else become derelict ; replace in slot", 2],
  ["draw random failures (0.5%/yr) → derelict ; replace in slot", 2],
  ["-- 3. external strike (once, at t = 5 yr) --", 1],
  ["fragment struck satellite via SBM ; append fragments + super-particles", 2],
  ["-- 4. environment --", 1],
  ["remove objects with perigee < 200 km  (reentered)", 2],
  ["bin all objects by altitude (25 km bins)", 2],
  ["for each bin, for each class pair (i, j):", 2],
  ["λij = Ni Nj σij v_rel Δt / V      (avoidance multiplies λ by 0.01)", 3],
  ["accumulate E[secondaries] over fragment channels  →  R₀ estimator", 3],
  ["k ~ Poisson(λij) ; for each of the k sampled events:", 3],
  ["if catastrophic (>40 J/g): fragment both objects via SBM  (cascade)", 4],
  ["else: victim satellite → derelict  (sub-trackable kill)", 4],
  ["record time series: populations by class, ΔV, maneuvers, R₀, histograms", 1],
  ["output: R₀ estimate, event log, population histories", 0],
]);

const B = { style: BorderStyle.SINGLE, size: 4, color: "999999" };
const borders = { top: B, bottom: B, left: B, right: B };
const cell = (t, w, bold = false, shade = false) =>
  new TableCell({
    width: { size: w, type: WidthType.DXA }, borders,
    shading: shade ? { type: ShadingType.CLEAR, fill: "e8ecf5" } : undefined,
    margins: { top: 60, bottom: 60, left: 100, right: 100 },
    children: [new Paragraph({ children: [new TextRun({ text: t, font: FONT, size: 20, bold })] })],
  });
const table = (widths, rows) =>
  new Table({
    columnWidths: widths, width: { size: widths.reduce((a, b) => a + b), type: WidthType.DXA },
    rows: rows.map((row, i) =>
      new TableRow({ children: row.map((t, j) => cell(t, widths[j], i === 0, i === 0)) })),
  });

const t0 = table([2200, 3580, 3580], [
  ["Dimension", "Legacy orbital-capacity models (e.g., MOCAT)", "This framework"],
  ["System state", "Global multi-decade environmental equilibrium", "Single-event point-stability response"],
  ["Target scale", "Extrapolates aggregate background populations", "Direct operational control loop up to 10⁶ nodes"],
  ["Primary variable", "Post-mission-disposal (PMD) failure averages", "Geometric packing layout and active shell dispersion"],
  ["Velocity profile", "Simplified isotropic assumptions across broad orbital regions", "Localized kinetics resolved in 25 km spatial bins"],
]);

const t1 = table([3600, 2200, 3560], [
  ["Parameter", "Value", "Notes"],
  ["Shell altitude / inclination", "550 km / 53.0°", "Walker-delta, 10 planes x 10 slots (N=100 baseline)"],
  ["Satellite mass / drag area / Cd", "260 kg / 25 m² / 2.2", "25 m² = drag reference area (panels); collision hard-body radius 2 m (sigma = pi(ri+rj)^2)"],
  ["Station-keeping dead band", "± 500 m in semi-major axis", "Impulsive re-boost at band floor"],
  ["Drag uncertainty", "20% (1-sigma, per step)", "Multiplicative white noise on drag acceleration"],
  ["Design life / PMD success", "7 yr / 95%", "Retired satellites replaced in slot"],
  ["Random failure rate", "0.5% per yr", "Failed satellites become derelict (no disposal)"],
  ["Conjunction avoidance", "99% effective", "Applies to trackable objects (>10 cm) vs active satellites"],
  ["External impactor", "10 kg at 12 km/s, t = 5 yr", "Catastrophic per 40 J/g threshold"],
  ["Trackable / lethal thresholds", "Lc > 10 cm / 1–10 cm", "1–10 cm as weighted super-particles (400)"],
  ["Mean crossing velocity", "8 km/s", "Kinetic-theory collision rates, 25 km altitude bins"],
  ["Time step / horizon / seeds", "5 d / 100 yr / 30", "Mean-element secular propagation"],
]);

const tval = table([2900, 2100, 2100, 2260], [
  ["Quantity", "This work", "Reference value", "Reference"],
  ["J2 nodal regression, 550 km / 53°", "-4.489 °/day", "-4.49 °/day", "analytic [5]"],
  ["SBM trackable fragments, 270 kg event", "341", "341.7", "EVOLVE 4.0 [3]"],
  ["SBM trackable fragments, Iridium-Cosmos-scale event (1,460 kg)", "1,211", "~2,300 cataloged (SBM known to underpredict this event)", "[3], catalog"],
  ["Derelict decay time from 550 km (tumbling-averaged area)", "1.1 yr", "1–5 yr observed (Starlink-class)", "operational data; model atmosphere is dense-side"],
  ["Altitude dependence of debris persistence", "clearing in yrs at 550 km; decades-scale tail above 800 km", "LEO instability concentrated above ~800 km", "LEGEND [8]"],
  ["Station-keeping Δv at 550 km", "~60 m/s/yr", "2–25 m/s/yr cycle-dependent", "self-consistent with the dense-side atmosphere that sets the 1.1 yr derelict decay"],
]);

const tsens = table([2800, 1800, 1800, 2960], [
  ["Parameter (baseline)", "Variation", "R₀ at N = 10,000", "Interpretation"],
  ["Avoidance effectiveness (99%)", "disabled (0%)", "9.5×10⁻¹", "control-loop ablation: ~160x, feedback-amplified"],
  ["", "90%", "2.4×10⁻²", "4x baseline"],
  ["", "99.9%", "4.5×10⁻³", "0.75x: saturates (derelict-fragment channel unaffected)"],
  ["Altitude bin width (25 km)", "12.5 km", "5.0×10⁻³", "-16%"],
  ["", "50 km", "3.4×10⁻³", "-43%"],
  ["Time step (5 d), subcritical", "2.5 d", "4.7×10⁻³", "-22%: within seed spread"],
  ["Time step, feedback regime (pessimistic, 40 yr)", "2.5 / 5 / 10 d", "5.9 / 4.3 / 2.2", "dt = 5 d within ~30% of finest; coarse steps bias low (conservative)"],
  ["Atmospheric density (1.0x)", "0.3x (solar-min proxy)", "2.1×10⁻¹", "36x: slow clearing of fragments and derelicts"],
  ["", "3.0x (solar-max proxy)", "7.8×10⁻⁴", "0.13x: fast clearing"],
  ["Mean crossing velocity (8 km/s)", "4 km/s", "2.2×10⁻³", "~linear in v_rel"],
  ["", "12 km/s", "9.4×10⁻³", "~linear in v_rel"],
  ["SBM fragment count (1.0x)", "2.0x", "8.5×10⁻³", "~1.4x (single seed, within spread)"],
  ["Derelict tumbling area (12.5 m²), at N = 10⁵", "25 m² (0.6 yr life)", "0.05", "leading systematic:"],
  ["", "12.5 m² (1.1 yr)", "0.31", "R₀ spans a factor of ~35"],
  ["", "6.25 m² (2.2 yr)", "1.7", "across the criticality line"],
  ["Seed replication, N = 25,000", "10 seeds, 100 yr", "(2.8 ± 1.7)×10⁻²", "60% spread"],
  ["Seed replication, N = 100,000", "9 seeds, 40 yr", "0.31 ± 0.09", "29% spread"],
  ["Pessimistic operations, N = 25,000", "90% avoid, 85% PMD, 2%/yr fail, 0.7x density", "7.8–9.8 (2 seeds)", "SUPERCRITICAL at fixed geometry"],
]);

const t2 = table([2340, 2340, 2340, 2340], [
  ["N (single shell)", "R₀ (E[fragment-involved secondaries])", "Sampled events", "Source"],
  ["100", "(6.2 ± 1.6)×10⁻⁵", "0 (30 seeds, 100 yr)", "simulation"],
  ["316", "(1.5 ± 0.3)×10⁻⁴", "0 (4 seeds)", "simulation, 100 yr"],
  ["1,000", "(4.7 ± 0.4)×10⁻⁴", "0 (4 seeds)", "simulation, 100 yr"],
  ["3,162", "(1.3 ± 0.1)×10⁻³", "0 (4 seeds)", "simulation, 100 yr"],
  ["4,400 (Starlink-Gen1 scale)", "(2.2 ± 0.8)×10⁻³", "0 (4 seeds)", "simulation, 100 yr"],
  ["10,000", "(6.0 ± 2.5)×10⁻³", "0–1 catastrophic per run (4 seeds)", "simulation, 100 yr"],
  ["25,000", "(2.8 ± 1.7)×10⁻² (10 seeds)", "up to 11 events per run", "direct simulation, 100 yr"],
  ["50,000", "(3.5 ± 1.4)×10⁻² (4 seeds)", "derelict-mediated events present", "direct simulation, 40 yr"],
  ["100,000", "0.31 ± 0.09 (9 seeds)", "~100–160 events per run", "direct simulation, 40 yr"],
  ["150,000", "1.03 (1 seed)", "≈ criticality", "direct simulation, 30 yr"],
  ["200,000", "1.92 ± 0.08 (3 seeds)", "supercritical", "direct simulation, 25 yr"],
  ["1,000,000 (one shell)", "≈140 by +3 yr (supercritical; all seeds cross 1 within 1 yr)", "~440 catastrophic; ~28,000 debris kills in 3 yr", "direct simulation, dt = 10 d"],
  ["1,000,000 (across 40 shells)", "2.8×10⁻² per shell", "equals N = 25,000 row", "direct simulation, 100 yr"],
]);

const t3 = table([4680, 2340, 2340], [
  ["Metric (N=100, 100 yr, 30 runs)", "Mean", "Notes"],
  ["Probability of any secondary collision", "0.00", "0/30 runs"],
  ["Cascade multiplier R₀", "3.5×10⁻⁵", "analytic expectation"],
  ["Trackable fragments (peak / at 100 yr)", "341 / ~0", "SBM expectation 341.7; integer truncation per event yields 341 discrete objects"],
  ["Fragment-cloud half-life", "0.84 yr", "550 km source altitude"],
  ["Active capacity at 100 yr", "99.0%", "replacement cycle active"],
  ["Station-keeping Δv", "~60 m/s per yr", "static mean atmosphere (conservative)"],
  ["Satellites lost to 1–10 cm debris", "0.0", "expected value ~0.03"],
]);

// ---------- content ----------
const children = [
  new Paragraph({ alignment: AlignmentType.CENTER, spacing: { before: 200, after: 200 },
    children: [new TextRun({ text: "Collisional-Cascade Risk in an Actively Managed LEO Mega-Constellation: A 100-Year Monte Carlo Assessment of Single-Breakup and Shell Self-Ignition Scenarios", font: FONT, size: 34, bold: true })] }),
  new Paragraph({ alignment: AlignmentType.CENTER, spacing: { after: 60 },
    children: [new TextRun({ text: "Vikas Yadav", font: FONT, size: 24 })] }),
  new Paragraph({ alignment: AlignmentType.CENTER, spacing: { after: 300 },
    children: [new TextRun({ text: "Draft manuscript — July 2026 — citations and figures to be finalized", font: FONT, size: 20, italics: true, color: "666666" })] }),

  h1("Abstract"),
  p("Proposals for low-Earth-orbit (LEO) mega-constellations now reach the million-satellite scale. This paper asks one question: does active operational control — station-keeping, autonomous collision avoidance, replacement, and disposal, modeled as a closed feedback loop rather than as aggregate compliance statistics — change the threshold at which collisional cascading (the Kessler syndrome) becomes self-sustaining? We embed the control loop directly in a stochastic orbital-propagation and fragmentation framework, subject managed 550 km Walker shells to a single external debris strike, and measure the cascade multiplier R₀ — expected secondary collisions per breakup — across shell populations from 10² to 10⁶. The answer is yes, decisively. Under baseline operations R₀ grows near-linearly with shell population until derelict production compounds it, and the criticality crossing is bracketed by direct simulation at N_crit ≈ 1.4×10⁵ per shell: a million satellites confined to one shell self-ignite within a year of the strike, while the same fleet dispersed across 40 shells operates a factor of ~35 below criticality. Degrading operations alone — poorer avoidance, disposal, and reliability at fixed geometry — collapses that margin by a factor of ~300, making operational control quality co-dominant with shell dispersion in setting the threshold. The leading model systematic (the derelict drag area) is quantified explicitly, the integrated framework is validated against LEGEND's published legacy-environment results, and every result reproduces from the released open-source code in minutes. The scope of the conclusion matters: this is not a finding that million-satellite fleets are safe, but a quantification of the specific architectural and operational conditions under which one class of them can be — a design requirement, not a reassurance."),
  p([r("Keywords: ", { bold: true }), r("space debris; Kessler syndrome; mega-constellations; NASA breakup model; Monte Carlo simulation; orbital capacity")]),

  h1("1. Introduction"),
  p("Kessler and Cour-Palais [1] first showed that collisions between artificial satellites could become the dominant source of orbital debris, and that above a critical spatial density the debris population grows through collisional cascading even without further launches [2]. The question has acquired new urgency: operational constellations already exceed ten thousand satellites, and in January 2026 SpaceX filed with the U.S. Federal Communications Commission for an orbital data-center constellation of up to one million satellites operating between 500 and 2,000 km [16], alongside its pending application for a 100,000-satellite third-generation Starlink system [17]. The million-satellite regime has thus moved from thought experiment to regulatory docket. At such scales intuition is an unreliable guide — LEO is vast, but fragmentation debris is prolific and fast — and quantitative cascade analysis becomes a prerequisite for both licensing and design."),
  p("Most debris-environment analyses model the full historical population, including rocket bodies and legacy debris, as detailed in the related work reviewed in Section 2.2; readers new to orbital debris will find the necessary background in Section 2.1. Here we isolate a narrower, sharper question: if a well-designed, actively controlled constellation is struck once by an external debris object, does the resulting fragment cloud propagate into a cascade within the constellation itself? The single-event framing is a deliberate scientific choice, not a claim about the real environment: the background population continuously supplies impactors, and Section 5 quantifies the resulting strike rate, showing that our per-event multipliers compose with that Poisson stream. What the framing isolates is the marginal risk attributable to the constellation's own population density and operations — the quantities most directly controlled by design. Figure 6 summarizes the central result of the paper."),
  p("We make three contributions: (i) the operational control loop as a first-class model element — station-keeping, autonomous conjunction avoidance, in-slot replacement, and post-mission disposal simulated as an explicit closed feedback loop acting on every satellite at every time step (Section 3.2), rather than as the aggregate compliance averages used by evolutionary debris models; (ii) a 100-year Monte Carlo characterization of constellation health and fragment-cloud evolution after a representative strike, resolved through that loop; and (iii) an empirical scaling law for the cascade multiplier R₀ as a function of constellation size, simulated directly to the million-satellite regime, together with an ablation study quantifying how much of the cascade margin the control loop itself provides."),

  h1("2. Background and Related Work"),
  h2("2.1 Background: orbits, debris, and the Kessler mechanism"),
  p([r("This subsection provides, for readers outside the orbital-debris community, the physical background the paper rests on; specialists may proceed to Section 2.2. ", {}),
     r("Orbits and collision energy. ", { bold: true }),
     r("A satellite in low Earth orbit (LEO, roughly 200–2,000 km altitude) circles the planet every ~95 minutes at about 7.6 km/s. Two objects in different orbits at the same altitude can therefore meet at relative speeds up to ~15 km/s; at such speeds a 1 kg fragment carries the energy of roughly 25 kg of TNT, which is why collisions between whole satellites do not dent them but shatter them into thousands of pieces. The community calls a collision 'catastrophic' when the impact energy exceeds about 40 J per gram of target mass — enough to fragment the target entirely rather than merely cratering it.")]),
  p([r("Perturbations: gravity's shape and the whisper of air. ", { bold: true }),
     r("Two forces slowly reshape every LEO orbit. First, Earth is not a perfect sphere; its equatorial bulge (the 'J2' effect) makes each orbital plane slowly pivot around the pole, a precession of several degrees per day whose rate depends on altitude and tilt — so two clouds of debris at slightly different altitudes gradually smear apart into a shell enclosing the whole planet. Second, even at 550 km a wisp of atmosphere remains, roughly a trillion times thinner than at sea level, yet over months it drains orbital energy and lowers satellites until they reenter and burn up. Crucially, this drag falls off exponentially with altitude: debris at 550 km clears itself within years, while debris at 800–1,000 km persists for decades to centuries. Altitude is therefore the single most consequential design choice in this paper.")]),
  p([r("Debris, trackability, and derelicts. ", { bold: true }),
     r("Ground radars reliably track orbiting objects larger than about 10 cm, and operational satellites can be warned and moved out of their way. Fragments of 1–10 cm are the dangerous middle class: too small to track, large enough to destroy a satellite on impact. Below 1 cm, shielding can help. A 'derelict' is a satellite that has died on orbit — it can no longer maneuver, dodge, or dispose of itself, and from the environment's perspective it is simply a very large piece of debris. Post-mission disposal (PMD) — deorbiting a satellite at end of life — is the practice that prevents derelict accumulation, and its success rate turns out to be one of the most important numbers in this paper.")]),
  p([r("The Kessler syndrome and the cascade multiplier. ", { bold: true }),
     r("Kessler and Cour-Palais observed in 1978 that collisions make fragments, and fragments make further collisions more likely — a chain reaction in slow motion. Whether the chain sustains itself is captured by a single number, directly analogous to the reproduction number of an epidemic: we call it R₀, the expected number of secondary collisions caused by one fragmentation event over the lifetime of its debris cloud. If R₀ < 1 the disturbance dies out; if R₀ > 1 collisional activity grows without further input — the Kessler syndrome proper. Everything in this paper is, at bottom, a measurement of R₀ and of the design and operational choices that move it.")]),
  p([r("Mean-field models and criticality. ", { bold: true }),
     r("One more idea from statistical physics appears in Section 4.4 and deserves a plain-language introduction. A 'mean-field' model replaces the tracking of every individual object with a single averaged quantity — here, the average rate at which one fragment finds a collision partner — much as an epidemiologist models an outbreak with average infection rates rather than following every person. The payoff is a compact formula for how risk grows with population. The key intuition is compound interest: one breakup creates fragments; those fragments cause a few collisions; each of those collisions creates its own fragments, which cause further collisions, and so on. If each 'generation' of collisions is smaller than the last (each producing, say, a fraction r < 1 of its parent's activity), the total settles to a finite sum — mathematically the geometric series 1 + r + r^2 + ..., which adds up to 1/(1-r). But if each generation matches or exceeds the last (r reaching 1), the sum diverges: the chain reaction sustains itself. Because r grows with the number of satellites N in the shell, there is a specific population N* at which r reaches 1. That is the 'mean-field closure' of Section 4.4 — Equation (5) is nothing more than the linear growth law multiplied by the compound-interest factor — and N* is the predicted critical population, the same mathematics that defines the critical mass of a nuclear reactor or the epidemic threshold of a disease.")]),
  p([r("Mega-constellations and the operational control loop. ", { bold: true }),
     r("A modern constellation such as Starlink arranges thousands of satellites in a Walker pattern: multiple orbital planes evenly spaced around the pole, satellites evenly phased within each plane, so that no two ever approach each other by design. Holding that pattern requires continuous, small corrections — 'station-keeping' — because drag constantly tugs satellites downward, plus autonomous dodging of tracked debris, replacement of retired satellites, and disposal at end of life. This paper's central move is to simulate that entire operational loop explicitly, satellite by satellite and week by week, and to ask how well it contains a fragmentation event at populations from one hundred satellites to one million.")]),
  h2("2.2 Related work"),
  p("The foundational literature established both the mechanism and the threshold character of collisional cascading. Kessler and Cour-Palais [1] computed collision frequencies for the 1978 catalog population and predicted the formation of a debris belt; Kessler [2] later formalized the notion of a critical density above which the debris population grows without further launches — the regime now bearing his name. NASA's engineering lineage produced the EVOLVE and LEGEND evolutionary models and, importantly for the present work, the Standard Breakup Model of EVOLVE 4.0 [3], which remains the community reference for fragment size, area-to-mass, and ejection-velocity distributions. Using LEGEND, Liou and Johnson demonstrated that the then-existing LEO population was already collisionally unstable above roughly 800 km even under a no-further-launch assumption [4], [8], establishing that altitude — through the atmospheric drag sink — is the dominant environmental variable in cascade dynamics."),
  p("A second wave of studies addressed the mega-constellation era directly. Lewis, Radtke, and Rossi [9] showed the debris environment to be acutely sensitive to large-constellation deployment parameters, identifying post-mission-disposal (PMD) compliance as the single most influential mitigation lever; Radtke et al. [10] reached similar conclusions for the OneWeb architecture specifically. Le May et al. [11] computed collision probabilities for the proposed broadband constellations against the background debris flux, and Rossi et al. [12] developed short- and long-term analysis tools spanning constellation deployment through end-of-life. Boley and Byers [13] broadened the assessment beyond collision risk to atmospheric and astronomical impacts, arguing that constellation scale itself is a governance problem. Collectively these studies treat the constellation as a source term added to the historical environment; the response of the managed system itself — station-keeping, avoidance, replacement, disposal — is typically represented by aggregate compliance parameters rather than an operating control loop."),
  p("Most recently, the orbital-capacity literature has reframed the question from environment projection to carrying capacity. D'Ambrosio, Lifson, and Linares [14] introduced multi-shell, multi-species source-sink models (MOCAT-3 and successors) that define capacity via the stable equilibria of the debris-satellite system, and the associated open-source Monte Carlo tool MOCAT-MC [15] propagates full object populations with probabilistic failures and collisions. MOCAT-based analyses locate the unstable regime above roughly 600–800 km and find that even small PMD shortfalls have outsized effects at mega-constellation scale — conclusions our results reproduce from the opposite direction. The two model families differ in emphasis rather than in kind, and the distinction should be stated fairly: MOCAT-MC already propagates individual objects with per-object probabilistic disposal and failures, so the increment here is narrower and specific — explicit dead-band station-keeping with Δv accounting, in-slot replacement, a modeled avoidance channel, and the single-event R₀ framing — while the modeled environment is deliberately far simpler than MOCAT's or LEGEND's (one shell, one inclination, one satellite class, no background population, no launch traffic). The present framework is therefore best read as a fast, operationally detailed complement to the environment models, resolving the localized point-stability response of a managed shell to a single fragmentation event, not as a replacement for them. The question addressed here is the single-event, managed-constellation response: rather than asking how a million satellites perturb the century-scale environment, we ask whether one fragmentation inside an actively controlled shell is self-amplifying, and how that answer scales with shell population. This complements global capacity models by isolating the marginal, design-controllable component of cascade risk within an explicitly modeled operational control loop; Section 3.2 specifies the loop's four controllers, and Section 4.5 measures their contribution by ablation. Table 1 summarizes the contrast."),
  t0,
  caption("Table 1. Positioning of this framework relative to legacy orbital-capacity models."),

  h1("3. Simulation Framework"),
  p("The complete simulation framework described in this section — propagation core, operational control loop, fragmentation and collision models, and all sweep and figure-generation drivers — is released as open-source software [18], so that every result reported in Section 4 can be reproduced directly from the published code."),
  h2("3.1 Constellation design"),
  p("The constellation is a Walker-delta shell [6] at 550 km altitude and 53.0° inclination, with satellites distributed uniformly over planes in right ascension and phased within planes so that nominal along-track and cross-plane separations are maximized. The baseline uses N = 100 satellites in 10 planes; N is a free parameter, exercised in this work from 10² to 10⁶. Satellites are Starlink-class: 260 kg, with two distinct area parameters that must not be conflated. The 25 m² figure is the drag reference area — the full projected area including solar panels, used only in the ballistic coefficient B = Cd A/m with Cd = 2.2. Collision kinetics instead use a 2 m hard-body radius representing the satellite bus, entering the pairwise combined cross-section as sigma = pi (ri + rj)^2 — approximately 50 m² for a satellite-satellite pair — which is the standard conservative envelope for catastrophic contact. The background-strike estimate of Section 5 deliberately uses the full 25 m² projected area, since debris arriving on uncontrolled trajectories can strike deployed panels as well as the bus. A third area applies to derelicts: once a satellite dies it tumbles, and its drag area switches to the orientation-averaged projected area of the deployed configuration, A/2 = 12.5 m² — the standard random-tumble average — giving a ballistic coefficient of 0.106 m²/kg and a decay time from 550 km of 1.1 years under this model's atmosphere, at the fast end of the observed 1–5 year range for Starlink-class derelicts (consistent with the deliberately dense static density profile). Because the derelict inventory drives the dominant collision channels at large N, this parameter is the model's leading systematic; Section 4.5 bounds it directly by varying the tumbling area over a factor of four."),
  h2("3.2 The operational control loop"),
  p("The central modeling choice is that constellation operations are represented as an explicit, closed feedback loop acting on every satellite at every time step, rather than as aggregate compliance statistics. The loop comprises four coupled controllers. (1) Station-keeping: stochastic drag continuously lowers each satellite's semi-major axis. When it falls 500 m below nominal (the control-band floor), an impulsive re-boost raises it to 500 m above nominal (the band ceiling) — a da = 1,000 m maneuver spanning the full ±500 m band — with Δv accounted as dv = (v/2)(da/a), the standard first-order cost of raising a near-circular orbit's semi-major axis by da at orbital speed v. Every active satellite is thereby held inside a ±500 m control band around its assigned slot for the full simulation. This is what makes the constellation 'non-colliding by design': active-active conjunctions are excluded by maintained geometry, not by assumption. (2) Conjunction avoidance: active satellites screen trackable objects (fragments and derelicts) and evade with 99% effectiveness, attenuating the corresponding collision channels by a factor of 100; the avoidance workload is accounted per maneuver. (3) Life-cycle management: satellites retire at a 7-year design life and are replaced in-slot, so constellation capacity is a controlled quantity; disposal succeeds with 95% probability. (4) The failure channel — the loop's leak: random failures (0.5% per year) and failed disposals produce derelicts that exit the control loop entirely; they cannot station-keep, dodge, or deorbit, and thereafter behave as one-satellite-mass debris objects, with their drag area switched to the tumbling-averaged value of Section 3.1. The 95% disposal-success and 0.5%/yr failure rates are deliberately conservative relative to reported large-constellation practice — recent ESA Space Environment Reports document rising PMD compliance, and Starlink operators report disposal success and on-orbit reliability well above these values [19] — so the derelict production simulated here should bound the modern-operator case from above. Every cascade result in this paper is a property of this loop: Section 4 shows that the channels the loop suppresses (active-fragment, active-derelict) are subdominant everywhere, while the loop's leak — the derelict population — dominates the residual risk and ultimately drives the supercritical transition at extreme densities. Section 4.5 quantifies the loop's value directly by ablation: disabling avoidance alone raises R₀ by a factor of ~160 at N = 10,000 (a feedback-amplified response, not a linear one), and degrading the entire loop simultaneously — avoidance, disposal, and reliability together — switches a 25,000-satellite shell from R₀ = 0.028 to a deeply supercritical R₀ ≈ 8–10 (Section 4.6; Table 6)."),
  h2("3.3 Orbit propagation"),
  p("Objects are propagated in mean orbital elements with a 5-day step over 100 years. Secular J2 nodal regression follows"),
  new Paragraph({
    alignment: AlignmentType.CENTER, spacing: { before: 120, after: 160 },
    children: [new DMath({ children: [
      new MathFraction({ numerator: [new MathRun("dΩ")], denominator: [new MathRun("dt")] }),
      new MathRun(" = −"),
      new MathFraction({ numerator: [new MathRun("3")], denominator: [new MathRun("2")] }),
      new MathSubScript({ children: [new MathRun("J")], subScript: [new MathRun("2")] }),
      new MathRun(" n "),
      new MathSuperScript({
        children: [
          new MathRun("("),
          new MathFraction({
            numerator: [new MathSubScript({ children: [new MathRun("R")], subScript: [new MathRun("E")] })],
            denominator: [new MathRun("p")] }),
          new MathRun(")")],
        superScript: [new MathRun("2")] }),
      new MathRun(" cos i"),
    ] }), eqnum(1)],
  }),
  p("Every symbol here has a direct physical reading. Omega is the right ascension of the ascending node — the compass heading at which the orbital plane crosses the equator — so its time derivative is the rate at which the whole plane pivots about Earth's axis. J2 = 1.0826×10⁻³ is the dimensionless coefficient quantifying Earth's equatorial bulge; n = sqrt(mu/a^3) is the mean motion, the satellite's orbital angular frequency; RE is Earth's equatorial radius; p = a(1 — e^2) is the semi-latus rectum, effectively the orbital radius for near-circular orbits; and i is the inclination, the orbit's tilt with respect to the equator. The cos i factor means low-inclination planes precess fastest and polar planes barely at all, while the (RE/p)^2 factor makes the effect fade with altitude. The argument of latitude advances at the Keplerian mean motion; J2 secular corrections to the in-plane angles are omitted, as they are immaterial to the population statistics used here. Atmospheric drag uses a piecewise-exponential density model [5] evaluated at perigee altitude:"),
  new Paragraph({
    alignment: AlignmentType.CENTER, spacing: { before: 120, after: 160 },
    children: [new DMath({ children: [
      new MathFraction({ numerator: [new MathRun("da")], denominator: [new MathRun("dt")] }),
      new MathRun(" = −ρ("),
      new MathSubScript({ children: [new MathRun("h")], subScript: [new MathRun("p")] }),
      new MathRun(") B "),
      new MathRun("√(μa)"),
    ] }), eqnum(2)],
  }),
  p("where a is the semi-major axis (the orbit's mean radius, so da/dt < 0 is orbital decay), rho(hp) is the atmospheric density at the perigee altitude hp, mu = GM is Earth's gravitational parameter, and B = Cd A/m is the ballistic coefficient — drag area per unit mass, the single number expressing how strongly the thin air brakes an object. A lightweight, flake-like fragment (large B) decays quickly; a dense intact satellite (small B) lingers. Eccentricity is damped proportionally, so apogee decays faster than perigee, circularizing the orbit as it descends. Path deviations are modeled as 20% (1-sigma) multiplicative white noise on the drag acceleration, representing atmospheric variability and maneuver execution errors. Objects with perigee below 200 km are removed as reentered. The J2-drag mean-element formulation reproduces the analytic nodal rate at the shell (-4.489 °/day simulated vs. -4.49 °/day analytic) and yields derelict decay times from 550 km of two to five years, consistent with observed Starlink-class lifetimes."),
  h2("3.4 Fragmentation model"),
  p("Catastrophic collisions (specific impact energy above 40 J/g) generate fragments per the NASA Standard Breakup Model [3], whose cumulative size distribution is"),
  new Paragraph({
    alignment: AlignmentType.CENTER, spacing: { before: 120, after: 160 },
    children: [new DMath({ children: [
      new MathRun("N(>"),
      new MathSubScript({ children: [new MathRun("L")], subScript: [new MathRun("c")] }),
      new MathRun(") = 0.1 "),
      new MathSuperScript({ children: [new MathRun("M")], superScript: [new MathRun("0.75")] }),
      new MathRun(" "),
      new MathSuperScript({
        children: [new MathSubScript({ children: [new MathRun("L")], subScript: [new MathRun("c")] })],
        superScript: [new MathRun("−1.71")] }),
    ] }), eqnum(3)],
  }),
  p("where N(>Lc) is the number of fragments with characteristic length larger than Lc (in meters) and M (in kg) is the total mass participating in the collision. The negative power law encodes the physics of shattering: halving the fragment size multiplies the count by 2^1.71, roughly 3.3, so every large fragment is accompanied by a swarm of small ones. Fragments larger than 10 cm are tracked individually; the 1–10 cm lethal-but-untrackable population is represented by 400 weighted super-particles. Area-to-mass ratios follow a lognormal distribution about the EVOLVE 4.0 trend, and ejection velocities follow the EVOLVE Δv distribution, log10(dv) ~ N(0.9 log10(A/m) + 2.9, 0.4) — that is, the base-10 logarithm of the ejection speed (m/s) is normally distributed with a mean that rises with the fragment's area-to-mass ratio and a standard deviation of 0.4 decades. Physically: flake-like fragments with high A/m are flung out at hundreds of m/s, while dense chunks receive gentler kicks. Each velocity kick is applied isotropically and mapped through the velocity perturbation to new element sets. For the baseline 270 kg catastrophic event — representing the combined mass of the 260 kg active satellite and the 10 kg external impactor — the NASA Standard Breakup Model yields an analytical expectation of 341.7 fragments above 10 cm, realized as 341 per event under integer truncation, and approximately 17,400 in the 1–10 cm class. Fragment masses are drawn independently from the size and area-to-mass distributions and are not renormalized to the parent mass; for the baseline event the drawn trackable-fragment masses sum to ~490 kg against the 270 kg parent, a factor-of-1.8 overdraw; enforcing exact mass conservation is a straightforward refinement that would not alter the collision statistics, which depend on fragment count and cross-section rather than mass."),
  h2("3.5 Collision kinetics"),
  p("Collision events are sampled per 25-km altitude bin using kinetic theory — the same mathematics that gives the collision rate of molecules in a gas. For object classes i and j sharing a bin, the expected number of collisions per time step is"),
  new Paragraph({
    alignment: AlignmentType.CENTER, spacing: { before: 120, after: 160 },
    children: [new DMath({ children: [
      new MathSubScript({ children: [new MathRun("λ")], subScript: [new MathRun("ij")] }),
      new MathRun(" = "),
      new MathFraction({
        numerator: [
          new MathSubScript({ children: [new MathRun("N")], subScript: [new MathRun("i")] }),
          new MathRun(" "),
          new MathSubScript({ children: [new MathRun("N")], subScript: [new MathRun("j")] }),
          new MathRun(" "),
          new MathSubScript({ children: [new MathRun("σ")], subScript: [new MathRun("ij")] }),
          new MathRun(" "),
          new MathSubScript({ children: [new MathRun("v")], subScript: [new MathRun("rel")] }),
          new MathRun(" Δt")],
        denominator: [new MathRun("V")] }),
    ] }), eqnum(4)],
  }),
  p("where Ni and Nj are the class populations in the bin; V is the bin's shell volume multiplied by sin i = 0.80, restricting it to the latitude band |lat| < 53° that an inclined population actually occupies (omitting this factor would understate densities by 25%); sigma_ij = pi (ri + rj)^2 is the combined cross-section — the effective 'target area' two objects of radii ri and rj present to each other — v_rel = 8 km/s is the mean closing speed, Delta-t is the time step, and V is the bin's shell volume. The formula reads naturally: collisions per step = (number of pairs) x (target area) x (distance swept per step) / (volume shared). Each term is exact for a well-mixed population; Section 4.5 tests the assumptions behind each factor. Pair channels comprise active-fragment, active-derelict (both attenuated by 99% avoidance), derelict-fragment, derelict-derelict, fragment-fragment (all catastrophic), and active vs. sub-trackable debris (satellite-killing but non-catastrophic, producing a derelict). Events are drawn from Poisson distributions each step, with the per-bin expected count capped at 100 per step to bound the event-processing loop (the cap never binds below N ~ 10⁶ and biases sampled counts — not the analytic estimator — low at extreme density); each sampled catastrophic collision invokes the breakup model on the participating objects, enabling cascade feedback. Alongside the sampled events, the simulator accumulates the analytic expectation of fragment-involved collisions, which provides a low-variance estimator of the cascade multiplier R₀ even when sampled counts are zero. The scope of R₀ must be stated precisely: it sums the fragment-involved channels only (active–fragment, derelict–fragment, fragment–fragment), isolating the cascade attributable to the strike; catastrophic derelict–derelict and active–derelict collisions — the intrinsic activity of the shell itself — are reported separately as sampled event counts, and at large N they dominate total catastrophic activity. R₀ therefore understates total collision activity at high density, and the 'supercritical' classification below is conservative in that respect."),
  p("The isotropic well-mixed proxy deserves a direct justification for the channels that matter. The Walker constellation itself is highly structured, but the channels that dominate R₀ involve at least one fragment or derelict, and these populations lose the constellation's ordering rapidly: breakup ejection velocities scatter fragment semi-major axes, eccentricities, and inclinations, and differential J2 regression then disperses their nodes within months (the ring-to-shell transient of Figure 5). A fragment population randomized in node and phase encountering a shell of satellites is close to the textbook kinetic-theory configuration, so the proxy is most accurate precisely for the fragment-satellite and fragment-derelict channels that carry the cascade. The structured geometry matters most for active-active encounters, which the control loop excludes, and for same-shell active-derelict geometry, where co-rotating relative velocities are lower than 8 km/s; the v_rel sensitivity of Section 4.5 bounds that effect at a factor of two, linear."),
  h2("3.6 Scenario and Monte Carlo design"),
  p("At t = 5 years a 10 kg external debris object (representative of a legacy fragment on a crossing orbit) strikes one randomly selected active satellite at 12 km/s, a catastrophic event by a wide margin. Thirty Monte Carlo histories are run to 100 years for the baseline; the R₀ sweep uses four to ten seeds per population size, with the analytic estimator providing low-variance means. Time-step policy is set by regime: in the subcritical regime the dynamics are secular and a 5-day step is ample, while near and above criticality the step controls how often cascade feedback is sampled and matters quantitatively. All boundary-region production runs (N = 2.5×10⁴ to 2×10⁵) use dt = 5 d, shown in Section 4.5 to lie within ~30% of dt = 2.5 d even in the strongly supercritical pessimistic case; the N = 10⁶ runs use dt = 10 d, which understates supercritical rates by ~15% relative to dt = 10/2 d — a conservative bias that cannot affect the classification. Table 2 summarizes all parameters."),
  t1,
  caption("Table 2. Simulation parameters."),
  p("Algorithm 1 summarizes one complete Monte Carlo history, making explicit how the propagation physics (Section 3.3), the operational control loop (Section 3.2), the fragmentation model (Section 3.4), and the collision kinetics (Section 3.5) interleave within each time step. The implementation vectorizes steps 1 and 4 over the entire object population, which is what permits direct simulation at N = 10⁶."),
  algo1,
  caption("Algorithm 1. One Monte Carlo history. All per-object operations are vectorized; the released implementation [18] follows this structure directly."),
  h2("3.7 Verification and validation"),
  p("Table 3 benchmarks the framework against analytic results, the reference breakup model, and observed behavior. The propagator reproduces the analytic J2 nodal rate at the shell to 0.1%. The fragmentation module reproduces the EVOLVE 4.0 analytical count for the baseline event exactly (modulo integer truncation), and applied to an Iridium-Cosmos-scale event (1,460 kg combined mass) yields 1,211 trackable fragments against roughly 2,300 eventually cataloged. This factor-of-two underprediction of that specific collision is a documented property of the Standard Breakup Model itself — an inherited model bias, not an artifact of this implementation — and its consequence for our results is bounded directly by the 2x fragment-yield sensitivity row of Table 6, which doubles R₀ linearly. Simulated derelict decay from 550 km is 1.1 years with the tumbling-averaged drag area — at the fast end of the observed 1–5 year range, as expected under the dense-side static atmosphere, and treated as the leading systematic in Section 4.5 — and the altitude structure of debris persistence — years-scale clearing at 550 km with a decades-scale tail above 800 km (Figure 3) — matches the instability boundary identified by LEGEND studies [8]. Station-keeping Δv is 2–3x higher than cycle-average operational experience, consistent with the deliberately dense static atmosphere; this conservatism shortens debris lifetimes and is examined quantitatively in the density sweep of Section 4.5."),
  p("Beyond component checks, we performed an integrated end-to-end benchmark against the best-established published result in the field: LEGEND's no-new-launch projection for the legacy LEO environment [8]. The framework was run in a benchmark mode that disables the constellation and its control loop entirely and instead initializes a LEGEND-like legacy population — 2,500 intact derelicts with lognormal ~900 kg masses and 7,000 trackable fragments, distributed over a catalog-shaped altitude profile from 400 to 2,000 km — and lets the same propagation, collision-kinetics, and breakup machinery evolve it for a century with no further launches. Across three seeds the simulated catastrophic-collision rate over the first fifty years is 0.04–0.16 per year, bracketing LEGEND's published expectation of one catastrophic collision every five to nine years (0.11–0.20 per year), and the trackable-fragment population grows by a factor of 1.0–1.5 per century, consistent with LEGEND's finding of slow collisional growth of the legacy population even without new launches [8]. The integrated model thus reproduces the reference result for the environment it was not tuned to — using the identical code path that produces every constellation result in Section 4 — which we regard as the strongest available check short of a full population-file exchange with the LEGEND/MOCAT teams, identified as future work. The benchmark mode ships in the released code and reruns in seconds."),
  p("At operational-constellation scale, our results are also consistent with the published mega-constellation literature: at N = 1,000–10,000 we find R₀ ~ 1×10⁻⁴ to 1×10⁻³ (Table 4), i.e., intra-constellation cascade contributions one to four orders of magnitude below the background-driven collision risk that studies such as Le May et al. [11] and Radtke et al. [10] identify as dominant at these populations — in agreement with their shared conclusion that current-generation constellations threaten the environment primarily through disposal failure rather than self-collision. We emphasize the character of the LEGEND comparison above: it is a benchmark constructed to resemble LEGEND's initial conditions, not a formal reproduction from identical population files, so the agreement is semi-quantitative; a formal benchmark via population-file exchange, and one-to-one comparison against ORDEM flux products or MOCAT-MC scenario outputs (which require full background populations and launch traffic), are developed in Section 7."),
  tval,
  caption("Table 3. Verification and validation against analytic, reference-model, and observed values."),

  h1("4. Results"),
  h2("4.1 Constellation health"),
  p("The managed constellation maintains 99% of design capacity throughout the century (Figures 1 and 2): the replacement cycle absorbs retirements, random failures, and the strike loss. Station-keeping consumes roughly 60 m/s per satellite-year — conservative relative to operational experience because the static mean atmosphere is on the dense side of the solar cycle at 550 km. We note that this cascade-safety budget is energetically negligible: with electric propulsion (specific impulse ~1,600 s), 60 m/s per year on a 260 kg satellite corresponds to about 1 kg of propellant and ~40 kWh of electrical energy annually — roughly 4 W of continuous power — and individual avoidance maneuvers, at centimeters to meters per second each, add single-digit m/s per year even at high maneuver rates. Avoiding the cascade therefore costs the spacecraft power budget essentially nothing; the true cost of the control loop is operational (tracking, autonomy, and disposal reliability), not energy. Expected losses of active satellites to the sub-trackable fragment population are 0.03 satellites over the century; no such loss occurred in the sampled runs. The expected number of unmitigated satellite-fragment collision opportunities (avoidance workload proxy) remains below one conjunction-driven maneuver per satellite-decade after the initial cloud decays. We note the scope of this metric: it counts only conjunctions of active satellites with strike-generated fragments and with derelicts. Nominal intra-constellation conjunctions among actively phased satellites are excluded by construction, since Walker phasing renders them deterministic and margin-protected rather than stochastic; the real operational maneuver load, which also screens against background debris, is correspondingly higher."),
  img("fig1_population.png", 600, 367),
  caption("Figure 1. Population evolution by object class (mean and 5–95% envelope over 30 Monte Carlo runs). The external strike at t = 5 yr injects ~341 trackable and ~17,000 sub-trackable fragments; drag removes the trackable cloud within a decade."),
  img("fig4_health.png", 600, 382),
  caption("Figure 2. Constellation health over the 100-year horizon: active capacity, cumulative station-keeping Δv, collision-avoidance workload, and post-strike collision events."),
  h2("4.2 Fragment-cloud evolution"),
  p("The breakup produces the classic Gabbard signature (Figure 4): apogees raised and perigees depressed symmetrically about the parent period, with a high-Δv tail reaching above 2,000 km apogee. Differential nodal precession disperses the cloud from an orbital ring into a shell over months, visible as the RAAN-spread transient (Figure 5, right panel). Spatially, the cloud blooms across 300–1,000 km before drag sweeps it downward (Figure 3): the trackable population halves in 0.84 years and is essentially cleared within ten, while the highest-altitude, lowest-B tail persists longest. The sub-trackable population decays on a similar timescale at the source altitude; its high-altitude remnant persists for decades but at spatial densities too low to matter for the shell."),
  img("fig2_density_heatmap.png", 600, 333),
  caption("Figure 3. Trackable-fragment spatial density vs. altitude and time (single history). The constellation shell at 550 km is marked; drag clears the cloud from below upward."),
  img("fig3_gabbard.png", 540, 371),
  caption("Figure 4. Gabbard diagram of the fragment cloud immediately after the strike (suborbital fragments excluded)."),
  h2("4.3 Cascade response"),
  p("No secondary collision occurred in any of the thirty 100-year histories. The analytic cascade multiplier — the expected number of secondary catastrophic collisions caused by the parent breakup over the cloud lifetime — converges within a decade of the strike to R₀ = 3.5×10⁻⁵ for N = 100 (Figure 5, left panel): the single breakup falls short of self-replacement by more than four orders of magnitude. The dominant channel is fragment vs. derelict, since avoidance suppresses the fragment vs. active channel by two orders of magnitude; the derelict inventory (an equilibrium of one to two objects maintained by the 5% disposal failure and 0.5%/yr failure rates) is thus the constellation's principal contribution to its own cascade exposure."),
  img("fig5_kessler.png", 620, 200),
  caption("Figure 5. Cascade diagnostics: cumulative expected secondary collisions vs. the R₀ = 1 criticality threshold (left); Monte Carlo distribution of sampled secondary collisions (center); ring-to-shell RAAN dispersion of the cloud (right)."),
  h2("4.4 Scaling with constellation size"),
  p("Repeating the experiment at N = 316 through 10,000 in the same shell yields the cascade multipliers of Table 4 (multi-seed means with standard deviations throughout). Across this range a power-law fit gives R₀ proportional to N^0.99 with a fitted-exponent uncertainty of ±0.05 — consistent with the linear density scaling that kinetic theory predicts, mildly moderated by the drag sink. Because expected cascade growth compounds multiplicatively, R₀ in this regime also bounds the probability that a single strike initiates any secondary collision."),
  p("The framework's vectorized design permits direct simulation through the criticality boundary itself (Figure 6). At N = 25,000 (ten seeds, 100 years) the multiplier is R₀ = 0.028 ± 0.017. At N = 50,000 (four seeds) it is 0.035 ± 0.014; at N = 100,000 (nine seeds) 0.31 ± 0.09; at N = 150,000, 1.03; and at N = 200,000, 1.92 ± 0.08 (three seeds). The criticality crossing is therefore bracketed directly by simulation: R₀ = 1 falls between N = 10⁵ and 1.5×10⁵ under baseline operations, N_crit ≈ 1.4×10⁵ per shell, with no extrapolation or interpolation involved. The seed-to-seed spread grows toward the boundary — 60% at 25,000, 29% at 100,000 — because a single early derelict collision substantially reshapes an individual history, itself a signature of approach to criticality."),
  p("The mechanism of the accelerating departure from the near-linear law admits a compact mean-field description (see Section 2.1 for the underlying compound-interest intuition). In the linear regime, R₀ is proportional to the target density the fragment cloud encounters. Two populations that each scale with N then compound it: the derelict inventory (maintained by the 0.5%/yr failure rate and 5% disposal failures, cleared by drag on a 1.1-year timescale) and the rate of sub-trackable debris kills, which converts active, avoiding satellites into passive targets. Each fragment-involved collision also spawns a new fragment generation, so the total fragment exposure is amplified by the geometric series 1 + r + r^2 + ..., where the per-generation reproduction r grows with N. Closing the loop gives"),
  new Paragraph({
    alignment: AlignmentType.CENTER, spacing: { before: 120, after: 160 },
    children: [new DMath({ children: [
      new MathSubScript({ children: [new MathRun("R")], subScript: [new MathRun("0")] }),
      new MathRun("(N) = "),
      new MathFraction({
        numerator: [
          new MathRun("a "),
          new MathSuperScript({ children: [new MathRun("N")], superScript: [new MathRun("0.90")] })],
        denominator: [
          new MathRun("1 − N/"),
          new MathSuperScript({ children: [new MathRun("N")], superScript: [new MathRun("*")] })] }),
    ] }), eqnum(5)],
  }),
  p("which diverges — the cascade bifurcation — where the geometric series ceases to converge. We emphasize the standing of this closure: it is a mechanism statement, not a precision fit. The single-pole form captures the divergence but understates the mid-range enhancement (a least-squares fit of N* to the four boundary-region points gives 2.1×10⁵ yet underpredicts R₀ at 10⁵ by a factor of three), so the criticality location quoted in this paper is the directly simulated bracket N_crit ≈ 1.4×10⁵, not the fitted pole. Direct simulation at N = 10⁶ confirms deep supercriticality: across three seeds at dt = 10 d, expected fragment-involved secondaries reach ≈140 within three years of the strike, crossing the criticality threshold within the first post-strike year in every seed; sampled activity comprises ~440 catastrophic collisions and ~28,000 satellites lost to sub-trackable debris over that window (recall from Section 3.5 that R₀ excludes the derelict-derelict and active-derelict events, which dominate these sampled counts). At this density the single-event framing itself collapses: the shell's intrinsic derelict production makes it collisionally self-igniting irrespective of the external strike, which merely advances the onset. By contrast, distributing the same million satellites across 40 shells reduces each shell to the directly simulated N = 25,000 case, R₀ = 0.028 per shell — a factor of ~35 below criticality. The simulations therefore indicate that shell dispersion is the dominant stabilizing architectural variable, separating a self-igniting shell from a stable one."),
  t2,
  caption("Table 4. Cascade multiplier vs. constellation size. All entries are simulated; no extrapolated values remain."),
  img("paper_fig5_r0_scaling.png", 520, 371),
  caption("Figure 6. Scaling of the cascade multiplier with single-shell constellation size. The near-linear law (dotted, N^0.99) holds to N ~ 10⁴; direct simulation (squares) resolves the derelict-mediated superlinear regime through the criticality crossing, which is bracketed directly between 10⁵ and 1.5×10⁵ (shaded band). The mean-field form (dashed) is shown as a mechanism guide only. A single 10⁶ shell is deeply supercritical (triangle); the same fleet across 40 shells operates a factor of ~35 below criticality (diamond)."),
  t3,
  caption("Table 5. Baseline outcome summary."),

  h2("4.5 Sensitivity and convergence"),
  p("Table 6 varies each contested modeling assumption at N = 10,000 (baseline R₀ = (6.0 ± 2.5)×10⁻³ over four seeds; single seeds elsewhere unless noted). The mean crossing velocity enters the kinetic rates linearly and R₀ responds roughly linearly, so even the extreme assumption that all encounters occur at Walker co-planar-like geometry (v_rel = 4 km/s) changes no conclusion. Altitude bin width moves R₀ by less than a factor of two between 12.5 and 50 km, and halving the time step to 2.5 days moves it by ~20% at this subcritical density; the feedback-regime time-step ladder is reported separately below. Doubling the Standard Breakup Model fragment yield (the factor by which the SBM underpredicted the Iridium-Cosmos event) raises R₀ by ~1.4x within seed noise. The solar-cycle density proxy spans a factor of ~280 between 0.3x and 3.0x density — by far the largest physical-parameter sensitivity, since low density simultaneously lengthens fragment residence and derelict lifetime; the solar-minimum-like case reaches R₀ = 0.21 at only 10,000 satellites. The dominant model systematic is the derelict tumbling area: at N = 10⁵, quartering it from the full 25 m² to 6.25 m² (derelict lifetimes 0.6 to 2.2 yr) moves R₀ from 0.05 through 0.31 to 1.7 — a factor of ~35 spanning the criticality line — which is why the derelict drag area, not any kinetic-theory approximation, sets the accuracy of N_crit. Avoidance remains the control loop's strongest lever: disabling it raises R₀ by a factor of ~160 (to 0.95), an amplification that exceeds the 100x single-channel attenuation ceiling because removing avoidance triggers sampled catastrophic collisions whose fragments feed back into the rates — a nonlinear, feedback-driven response, not a linear one."),
  p("On convergence: the analytic R₀ estimator and the sampled event counts are mutually consistent throughout — runs with sampled catastrophic events sit in the upper tail of the estimator distribution, and zero-event runs are Poisson-consistent with their expectations. The feedback-regime time-step ladder, run on the strongly supercritical pessimistic case (Section 4.6) over a fixed 40-year window, gives R₀ = 5.9, 4.3, and 2.2 at dt = 2.5, 5, and 10 d: dt = 5 d (used for all boundary-region production) sits within ~30% of the finest step, while dt = 10 d underestimates by more than a factor of two — the reason boundary-region runs are never executed at coarse steps, and a conservative bias where coarse steps are used (N = 10⁶, where dt = 20 d gives 122 vs 146 at dt = 10 d, a 16% understatement that cannot affect the classification). The supercritical classification at N = 10⁶ is robust across all seeds, each crossing the criticality threshold within the first post-strike year and exceeding it a hundredfold within three."),
  tsens,
  caption("Table 6. Sensitivity of the cascade multiplier to modeling assumptions, at N = 10,000 unless noted."),

  h2("4.6 A pessimistic operations scenario"),
  p("The baseline parameters deliberately reflect a competent modern operator, and it is fair to ask how much of the reported stability they purchase. To bound this, we simulated a degraded-operations scenario at N = 25,000 per shell — the per-shell population of the dispersed million-satellite architecture — combining 90% avoidance effectiveness, 85% disposal success, a 2%/yr failure rate, and 0.7x atmospheric density (solar-minimum-like), all simultaneously. The result is deeply supercritical: R₀ = 7.8–9.8 across two seeds, with ~600 collision events sampled per century, dominated by active-derelict and derelict-derelict pairs feeding a growing fragment background. Comparing like geometry, operations quality alone moves R₀ from 0.028 to ~9 — a factor of roughly 300 — which exceeds the effect of any single physical parameter examined in Table 6 except the solar-cycle extreme it partially contains. Operational control quality is thus a co-dominant determinant of the cascade threshold, comparable in leverage to shell dispersion: the threshold is set jointly by architecture and by the integrity of the operational control loop, and neither alone suffices at extreme scale."),

  h2("4.7 The stability regime map"),
  p("The preceding sections vary shell population and operations quality separately; Figure 7 combines them into a regime map, constructed from a 4 x 5 grid of direct simulations spanning four operations levels (from 90% avoidance / 85% PMD / 2%/yr failures to 99.9% / 99% / 0.2%/yr) and shell populations from 10³ to 10⁶, with the R₀ = 1 crossing additionally bracketed by direct simulation on each row rather than inferred by interpolation. The brackets place the criticality boundary at N ≈ 2×10⁴ per shell under poor operations, ≈4×10⁴ under degraded operations, and ≈1.4×10⁵ at baseline; under excellent operations a single shell holding one million satellites remains marginal rather than supercritical (R₀ ≈ 0.6 at a truncated post-strike horizon), placing that row's boundary at or above 10⁶. Between brackets the shading is interpolated and should be read as indicative only — the divergence of R₀ near the boundary makes interpolated contour positions uncertain by a factor of ~1.5, which is why the direct brackets are drawn explicitly. The map locates today's operational systems deep in the stable region: Starlink Gen1-class shells (~1,600 satellites per shell) and Kuiper-class shells (~1,200) sit an order of magnitude or more below the marginal band in N, with additional margin from their demonstrated operations quality. The dispersed million-satellite architecture (25,000 per shell) is stable at baseline operations and deeply supercritical under degraded operations — the quantitative content of Section 4.6. OneWeb is plotted for population reference only: its 1,200 km altitude lies outside the 550 km drag environment assumed by the map, and the weak-drag penalty would shift its true position adversely. Read as a design chart, the map's message is that the two axes trade against each other along the boundary — roughly half a decade to a decade of shell population per operations tier — so capacity and operational discipline are partially interchangeable currencies for cascade margin, within the assumptions of the modeled architecture."),
  img("paper_fig7_regime_map.png", 580, 397),
  caption("Figure 7. Cascade-stability regime map from the 4 x 5 direct-simulation grid (dots), with the R₀ = 1 crossing additionally bracketed by direct simulation on each row (dark bars); shading between grid points is interpolated and indicative only. Overlaid cases mark current constellations and the million-satellite architectures studied here. OneWeb (asterisk) is shown for population reference only, as its altitude lies outside the map's 550 km drag assumptions."),

  h1("5. Discussion"),
  p("Three design levers explain the large sub-criticality margin. First, altitude: at 550 km the atmospheric residence time of fragmentation debris (half-life below one year for trackable fragments) is far shorter than the mean time between debris-generating events, so the environment is strongly self-cleaning; the same breakup at 800–1,200 km, where drag lifetimes reach decades to centuries, would yield a proportionally larger R₀ and is the regime in which historical studies find instability [8]. Second, dispersion: R₀ scales near-linearly with shell population at moderate densities and superlinearly beyond ~10⁴ per shell, so spreading a fixed fleet across shells buys margin more than one-for-one precisely where it matters most — our direct simulations show it is the difference between a supercritical single shell and a 40-shell architecture operating a factor of ~35 below criticality. Third, operations: avoidance suppresses the largest collision channel, and disposal compliance controls the derelict inventory that dominates the residual risk and drives the superlinear regime. These results indicate that a million-satellite LEO system is not intrinsically Kessler-critical within the modeled operational architecture, but neither is it automatically safe: its margin is an engineered quantity determined jointly by fleet packing and by operations quality (Section 4.6). None of these levers is expensive in spacecraft resources — Section 4.1 shows the entire station-keeping and avoidance budget amounts to a few watts of continuous power per satellite — so cascade safety competes with no other subsystem for mass or energy; the requirement is design attention rather than resources."),
  p("The single-event framing bounds, but does not close, the cascade question — and our large-N runs locate where it breaks. Strikes are not rare at scale, and a rough quantification is instructive. The cataloged >10 cm population implies a spatial density of order 2×10⁻8 objects per km3 in the constellation altitude band; against a 25 m² satellite cross-section at ~7.5 km/s closing speed, this gives an unmitigated catastrophic-encounter rate of order 1×10⁻⁴ per satellite-year. A million-satellite fleet therefore faces on the order of 100 catastrophic-class background encounters per year before mitigation; active satellites avoid nearly all of these, but the ~1% derelict fraction cannot, yielding roughly one background-driven fragmentation per year at full scale — a Poisson stream of exactly the events simulated here, each multiplied by the R₀ values of Table 4. Rigorous background-flux inputs (ORDEM [20] or ESA MASTER) and launch traffic should replace this estimate in future work. Because clouds at 550 km decay within a few years, successive sub-critical events do not accumulate at the shell unless their rate approaches the clearing rate; at one event per year against a ~1 yr cloud half-life, the dispersed 40-shell architecture retains its margin, though with less headroom than the single-event numbers alone suggest. More fundamentally, above roughly 10⁵ satellites per shell the constellation's intrinsic derelict production makes collisional activity self-starting, so the relevant stability question shifts from the response to an external perturbation to the equilibrium of the shell's own source and sink terms; a full assessment requires coupling this framework to a background-debris and launch-traffic evolutionary model, which Section 7 develops as the first future-work priority."),

  p("These results bear directly on plans now before regulators. SpaceX's January 2026 FCC filing for up to one million solar-powered orbital data-center satellites at 500–2,000 km [16] represents, alongside the 100,000-satellite Starlink Gen3 application [17], the first concrete industrial commitment to the population regime studied here — and, in our reading, an encouraging one. The filing's scale would bring unprecedented on-orbit computing and solar-energy utilization, and our results indicate the ambition is not intrinsically foreclosed by cascade physics — provided the fleet is dispersed, flown low, and operated to the standards modeled here: a single 550-km shell holding the full million is supercritical in our direct simulations, but the same fleet spread across roughly 40 shells sits a factor of ~35 below criticality per shell under baseline operations, and the filing's wide 500–2,000 km altitude range is precisely what makes such dispersion available. SpaceX's operational record — demonstrated autonomous conjunction avoidance, propulsive disposal at scale, and the highest PMD compliance rates yet observed — exercises precisely the levers our analysis identifies as decisive. The same analysis, however, sharpens the design question the filing leaves open: the upper portion of the proposed 500–2,000 km range lies in the weak-drag regime where fragment clouds persist for decades and the self-cleaning margin largely vanishes. A capacity-aware deployment that concentrates mass low, disperses it across shells, and reserves high shells for the smallest sustainable populations would let the million-satellite vision proceed on a defensible physical footing, and frameworks of the kind presented here — fast enough to sweep design space — are the natural tool for negotiating that architecture. Two caveats apply: the filing does not yet specify per-shell packing, so our dispersion conclusions describe the design space rather than the proposal itself; and cascade risk is only one axis of the broader impact assessment — astronomy, atmospheric effects of reentry at scale, and ground-casualty risk [13] lie outside this model's scope and warrant parallel scrutiny."),
  p("A brief note on power and thermal feasibility is warranted, since the proposed application — orbital data centers — inverts the usual spacecraft resource picture. Where cascade safety is energetically free (Section 4.1), compute is not. Solar flux in LEO delivers 1.36 kW/m2, or roughly 400 W/m2 of electrical power with modern cells; the filing's sun-synchronous inclinations maximize illumination fraction, and a 100 kW-class compute node still requires on the order of 250–300 m² of array, with megawatt-class nodes demanding arrays of several thousand square meters. Nuclear fission power does not relieve this: UN principles adopted after the Kosmos-954 reentry restrict reactors to orbits high enough that debris lifetimes exceed fuel decay times, which categorically excludes the self-cleaning low-altitude regime this paper identifies as cascade-safe — and a reactor requires large radiators regardless. Radiators, in fact, are the binding constraint: in vacuum, waste heat leaves only by radiation, at a net 200–300 W/m2 at electronics-compatible temperatures, so thermal rejection area matches or exceeds solar collection area at any compute density. The practical implication for cascade analysis is that data-center satellites will be physically large — hundreds to thousands of square meters of deployed area per spacecraft — which enlarges collision cross-sections and drag ballistic coefficients well beyond the 25 m² Starlink-class assumption used here. Both effects are first-order relevant (cross-section raises collision rates; large area-to-mass accelerates drag clearing and disposal), but they do not cancel: collision rates scale with the full deployed cross-section while the drag benefit saturates once disposal is already fast, so data-center-class satellites face a lower per-shell cascade-stability limit than the 25 m² telecom-class satellites analyzed here — the supercritical threshold located in Section 4.4 should be read as an upper bound for such architectures. Re-running the scaling analysis with data-center-class geometry is a directly supported extension of the published framework [18]."),

  h1("6. Limitations"),
  p("Several exclusions are intentional, and their rationale bears stating. Continuous launch traffic, the evolving background debris population, interactions between multiple operators, and correlated failure modes (a software fault or solar storm disabling many satellites simultaneously) are all omitted — not because they are unimportant, but because each couples the answer to assumptions about third parties, while the present design isolates the component of cascade risk that a single operator's architecture and operations control. The interpretive consequence is no longer claimed as a strict bound in either direction: the exclusions (background debris, launch traffic, other operators) all remove debris sources and therefore depress risk, while the audited internal approximations act in both directions — the latitude-band volume correction and feedback-regime time steps are handled conservatively, and the derelict drag area, the leading remaining systematic, is bounded explicitly by the factor-of-four sweep in Table 6 (longer-lived derelicts, at the slow end of observed lifetimes, would lower N_crit toward ~10⁵). Reported values should be read with those stated sensitivities rather than as one-sided bounds; the supercritical classification at 10⁶ per shell is robust across the entire audited range. Correlated failures deserve particular emphasis: the pessimistic scenario of Section 4.6 shows that a sustained 2%/yr failure rate is sufficient to ignite a 25,000-satellite shell, so an event that disabled even a few percent of a shell's population at once would produce a derelict spike well outside the envelope simulated here."),
  p("A related idealization is that active satellites never collide with one another, because station-keeping preserves the designed geometry exactly within the ±500 m control band. Real systems approach but do not reach this ideal: orbit-determination accuracy, ephemeris latency, maneuver-execution errors, and conjunction-screening uncertainty (operational probability-of-collision thresholds are set precisely because state knowledge is imperfect) leave a small residual active-active collision rate that the present model sets to zero. We expect this residual to be far below the derelict-mediated channels that dominate our results — operational experience across tens of thousands of satellite-years has produced no active-active collision — but at 10⁵-10⁶ satellites per shell even rare per-pair events could aggregate, and the effect enters R₀ as an additive floor rather than a multiplier. Incorporating navigation and execution error distributions into the control loop, so that the active-active channel is modeled rather than excluded, is a natural refinement of the framework."),
  p("The model omits the existing background debris population and non-constellation traffic, so all reported risk is the marginal, self-inflicted component; absolute collision rates in the real environment are higher. The static exponential atmosphere neglects solar-cycle density variation, which modulates both station-keeping cost and debris clearing times by factors of a few in either direction. During solar maximum, atmospheric expansion increases drag at 550 km by up to an order of magnitude, clearing fragment clouds substantially faster than the baseline model dictates; the static atmosphere therefore represents a conservative assessment of debris-clearing timelines over much of the cycle. Solar-minimum conditions, by contrast, lengthen the residence of fragments and derelicts simultaneously, and the density sweep of Section 4.5 shows this leverage is large — a factor of ~36 in R₀ at 0.3x density — so cycle phase materially moves the criticality boundary and is treated as a first-class sensitivity rather than a small correction. On the operations side, the same dense-side static profile makes the quoted station-keeping Δv conservative. A solar-cycle-resolved atmosphere is developed as a priority in Section 7."),
  p("The kinetic-theory collision sampler assumes a well-mixed population within each 25-km altitude bin, characterized by a single 8 km/s mean crossing velocity. A Walker-delta constellation is not well-mixed: it comprises ordered, near-parallel tracks along which intra-constellation relative velocities approach zero, punctuated by severe relative-velocity spikes at high-latitude planar crossings. The isotropic 8 km/s figure is a spatial-averaging proxy that balances these structural extremes — conservative for co-planar geometry, optimistic for head-on crossings — and is most defensible for the fragment-versus-satellite channels that dominate R₀, since post-breakup fragment orbits are rapidly randomized in node and phase. The large-N runs trade horizon for scale (40 years at N = 10⁵; three post-strike years at 10⁶ with dt = 10 d); the supercritical finding at 10⁶ is insensitive to this because expected secondaries exceed unity within the first year in every seed and grow monotonically, and the time-step ladder of Section 4.5 bounds the discretization bias as conservative, but longer histories at these scales would tighten the quantitative rates. Finally, fragment area-to-mass and Δv distributions are simplified relative to the full EVOLVE 4.0 implementation, and satellites are treated as single-body spheres for collision purposes."),

  h1("7. Future Research Directions"),
  p("The framework's speed makes several extensions immediately practical, listed here roughly in order of scientific priority. First, the coupled multi-event model: replace the single injected strike with a Poisson stream of background-driven fragmentations at the rate estimated in Section 5, sourced from ORDEM or MASTER flux, together with explicit launch traffic — converting the single-event stability map into a full dynamic capacity model and closing the principal gap with the evolutionary models. Second, a formal integrated benchmark: reproduce a published LEGEND or MOCAT-MC scenario from exchanged initial-condition population files rather than the resemblance-based construction of Section 3.7, upgrading the validation from semi-quantitative to formal. Third, derelict aerodynamics: the derelict drag area is the leading systematic of this study (Table 6), and calibrating a tumbling-attitude drag model against the growing body of observed Starlink-class decay tracks would collapse the factor-of-four uncertainty band around N_crit to the ~30% level of the remaining terms. Fourth, a solar-cycle-resolved atmosphere, whose factor-of-~280 leverage on R₀ at fixed geometry (Section 4.5) makes cycle-phase-aware licensing analysis both feasible and consequential. Fifth, closing the active-active channel: incorporate navigation-error, ephemeris-latency, and maneuver-execution distributions into the control loop so that the residual collision rate among controlled satellites is modeled rather than excluded (Section 6). Sixth, heterogeneous architectures: multi-inclination and multi-altitude fleets, and the large deployed geometries of data-center-class satellites (Section 5), whose cross-section-to-drag trade shifts the per-shell stability limit. Seventh, active debris removal as a fifth controller in the loop, targeting the derelict inventory that this study identifies as the cascade's engine — a direct test of removal-rate requirements as a function of shell population. Finally, on the theoretical side, the mean-field closure of Section 4.4 invites a proper branching-process derivation with generation-dependent reproduction, which would replace the qualitative single-pole form with a predictive theory of N_crit and connect orbital-cascade stability formally to the epidemic-threshold literature."),

  h1("8. Conclusion"),
  p("The question posed at the outset — whether an explicit operational control loop changes the cascade threshold — has a quantitative answer: it moves the threshold by roughly half a decade to a decade of shell population per tier of operations quality, and it is co-equal with architecture in setting the margin. Within the assumptions of the modeled operational architecture, a single external fragmentation event in an actively managed 550-km constellation does not initiate a collisional cascade at shell populations up to 10⁵, where direct simulation gives R₀ = 0.31 ± 0.09 over nine seeds; the criticality crossing is bracketed directly at N_crit ≈ 1.4×10⁵ per shell, a single 10⁶ shell is deeply supercritical with collisional activity that no longer damps out, and the same fleet dispersed across 40 shells operates at R₀ = 0.028 per shell — a factor of ~35 below criticality under baseline operations, and supercritical under degraded operations (Section 4.6). The underlying mechanism reduces to a balance sheet of debris injection against debris removal: packing density sets the injection-to-exposure product and drives R₀ near-linearly (N^0.99) at moderate densities and superlinearly beyond ~10⁴ per shell as the derelict inventory compounds, while the atmospheric drag sink at low altitude sets a fast, population-independent removal rate. At 550 km the removal side of the ledger wins comfortably below roughly 10⁵ satellites per shell; beyond that, derelict-mediated injection overtakes the fixed sink. Cascade margin is thus governed by four controllable factors — altitude (drag clearing), shell dispersion, disposal compliance, and avoidance capability — and erodes predictably as each is relaxed. A final word on scope, because the headline number invites misreading: nothing in this paper supports the unconditional statement that a million satellites are safe. The supported statement is conditional on every element studied here — altitude in the self-cleaning drag regime, dispersion across many shells, disposal compliance, avoidance capability, and sustained reliability — and Sections 4.5–4.7 quantify how the margin collapses, by orders of magnitude, when individual conditions are relaxed. The result is a design requirement, not a reassurance. The framework presented here runs a century of constellation-plus-debris evolution in seconds per history, making it suitable for direct million-object simulation, multi-shell design optimization, and coupling to background-environment models in future work. The immediate extensions are a multi-event assessment driving the framework with a realistic Poisson stream of background strikes, a solar-cycle-resolved atmosphere, and multi-seed replication at N = 10⁶ — together these convert the single-event stability map presented here into a full dynamic capacity model for the million-satellite era."),
  p("Because the licensing debate this work informs is ultimately public, we have paired the technical analysis with a science-communication companion: a one-page poster that presents the same results — the domino-score (R₀) framing of cascade risk, the growth of risk with packing density, the supercriticality of a single overcrowded shell versus the safety of a dispersed fleet, and the self-cleaning action of the low-altitude atmosphere — in language and visuals accessible to a general audience, including school-age readers. The poster reproduces the Figure 6 scaling result and the fragment-decay history of Figure 1 in simplified form, with all numbers drawn directly from the simulations reported here. We regard such companion artifacts as part of the responsible dissemination of orbital-capacity research, given the level of public concern that the term Kessler syndrome now attracts."),

  h1("Data and Code Availability"),
  p([r("A further contribution of this work is the simulation infrastructure itself. The complete simulator — propagation core, control loop, breakup and collision models, sweep drivers, and every figure-generation script used in this paper — is released as open-source software (MIT license) at "), r("https://github.com/vikasy/leo-kessler-sim", { bold: true }), r(" [18]. A century of constellation-plus-debris evolution runs in seconds per history at N = 10⁴ and in roughly twenty seconds at N = 10⁶ on a laptop-class CPU — no high-performance computing cluster is required. This speed comes from the implementation strategy rather than approximation: the object population is stored as a structure-of-arrays and every per-object operation (propagation, control-loop triggers, binning, rate accumulation) is expressed as fully vectorized NumPy array broadcasting, so each time step costs a handful of array operations regardless of whether the population is one hundred or one million. Every entry in Tables 4 and 6, including the supercritical million-satellite case, is therefore reproducible in minutes with the commands documented in the repository README. The outreach poster described in Section 8 and the manuscript build script are included in the same repository.")]),

  h1("References"),
  p("[1] Kessler, D. J., and Cour-Palais, B. G., \"Collision Frequency of Artificial Satellites: The Creation of a Debris Belt,\" Journal of Geophysical Research, Vol. 83, No. A6, 1978, pp. 2637-2646. doi:10.1029/JA083iA06p02637", { alignment: AlignmentType.LEFT }),
  p("[2] Kessler, D. J., \"Collisional Cascading: The Limits of Population Growth in Low Earth Orbit,\" Advances in Space Research, Vol. 11, No. 12, 1991, pp. 63-66.", { alignment: AlignmentType.LEFT }),
  p("[3] Johnson, N. L., Krisko, P. H., Liou, J.-C., and Anz-Meador, P. D., \"NASA's New Breakup Model of EVOLVE 4.0,\" Advances in Space Research, Vol. 28, No. 9, 2001, pp. 1377-1384.", { alignment: AlignmentType.LEFT }),
  p("[4] Liou, J.-C., and Johnson, N. L., \"Risks in Space from Orbiting Debris,\" Science, Vol. 311, No. 5759, 2006, pp. 340-341. doi:10.1126/science.1121337", { alignment: AlignmentType.LEFT }),
  p("[5] Vallado, D. A., Fundamentals of Astrodynamics and Applications, 4th ed., Microcosm Press, Hawthorne, CA, 2013.", { alignment: AlignmentType.LEFT }),
  p("[6] Walker, J. G., \"Satellite Constellations,\" Journal of the British Interplanetary Society, Vol. 37, 1984, pp. 559-572.", { alignment: AlignmentType.LEFT }),
  p("[7] Brouwer, D., \"Solution of the Problem of Artificial Satellite Theory Without Drag,\" The Astronomical Journal, Vol. 64, 1959, pp. 378-397.", { alignment: AlignmentType.LEFT }),
  p("[8] Liou, J.-C., and Johnson, N. L., \"Instability of the Present LEO Satellite Populations,\" Advances in Space Research, Vol. 41, No. 7, 2008, pp. 1046-1053.", { alignment: AlignmentType.LEFT }),
  p("[9] Lewis, H. G., Radtke, J., Rossi, A., et al., \"Sensitivity of the Space Debris Environment to Large Constellations and Small Satellites,\" Proceedings of the 7th European Conference on Space Debris, ESA/ESOC, Darmstadt, 2017.", { alignment: AlignmentType.LEFT }),
  p("[10] Radtke, J., Kebschull, C., and Stoll, E., \"Interactions of the Space Debris Environment with Mega Constellations - Using the Example of the OneWeb Constellation,\" Acta Astronautica, Vol. 131, 2017, pp. 55-68.", { alignment: AlignmentType.LEFT }),
  p("[11] Le May, S., Gehly, S., Carter, B. A., and Flegel, S., \"Space Debris Collision Probability Analysis for Proposed Global Broadband Constellations,\" Acta Astronautica, Vol. 151, 2018, pp. 445-455.", { alignment: AlignmentType.LEFT }),
  p("[12] Rossi, A., Petit, A., and McKnight, D., \"Short-Term Space Safety Analysis of LEO Constellations and Clusters,\" Acta Astronautica, Vol. 175, 2020, pp. 476-483.", { alignment: AlignmentType.LEFT }),
  p("[13] Boley, A. C., and Byers, M., \"Satellite Mega-Constellations Create Risks in Low Earth Orbit, the Atmosphere and on Earth,\" Scientific Reports, Vol. 11, 2021, Art. 10642. doi:10.1038/s41598-021-89909-7", { alignment: AlignmentType.LEFT }),
  p("[14] D'Ambrosio, A., Lifson, M., and Linares, R., \"The Capacity of Low Earth Orbit Computed Using Source-Sink Modeling,\" arXiv:2206.05345, 2022.", { alignment: AlignmentType.LEFT }),
  p("[15] MIT ARCLab, \"MOCAT-MC: MIT Orbital Capacity Assessment Toolbox, Monte Carlo,\" open-source software, https://github.com/ARCLab-MIT/MOCAT-MC, accessed July 2026.", { alignment: AlignmentType.LEFT }),
  p("[16] Foust, J., \"SpaceX Files Plans for Million-Satellite Orbital Data Center Constellation,\" SpaceNews, February 2026 (FCC filing of January 30, 2026).", { alignment: AlignmentType.LEFT }),
  p("[17] \"SpaceX Wants to Launch 100,000 Starlink Satellites to Orbit,\" Space.com, 2025 (FCC application for third-generation Starlink).", { alignment: AlignmentType.LEFT }),
  p("[18] Yadav, V., \"leo-kessler-sim: Monte Carlo Simulator for Collisional-Cascade Risk in Managed LEO Mega-Constellations,\" open-source software (MIT license), https://github.com/vikasy/leo-kessler-sim, 2026. [Archival DOI to be assigned via Zenodo upon release v1.0.]", { alignment: AlignmentType.LEFT }),
  p("[19] European Space Agency Space Debris Office, \"ESA's Annual Space Environment Report,\" ESA/ESOC, Darmstadt, latest edition (PMD compliance and disposal-success statistics).", { alignment: AlignmentType.LEFT }),
  p("[20] Krisko, P. H., \"The New NASA Orbital Debris Engineering Model ORDEM 3.0,\" AIAA/AAS Astrodynamics Specialist Conference, AIAA 2014-4227, 2014.", { alignment: AlignmentType.LEFT }),
];

const doc = new Document({
  styles: { default: { document: { run: { font: FONT, size: 22 } } } },
  sections: [{
    properties: { page: { size: { width: 12240, height: 15840 },
      margin: { top: 1440, bottom: 1440, left: 1440, right: 1440 } } },
    children,
  }],
});

Packer.toBuffer(doc).then((buf) => {
  fs.writeFileSync("kessler_constellation_paper.docx", buf);
  console.log("wrote kessler_constellation_paper.docx");
});
